dist: xenial
language: python

python:
  - "3.6"
  - "3.7"

install:
  - curl --fail -L https://github.com/TankerHQ/dmenv/releases/download/v0.16.1/dmenv-linux -o dmenv
  - chmod u+x dmenv
  - export PATH=${PATH}:${pwd}
  - dmenv install

script:
  - ./ci.sh
  - codecov
