[tool.poetry]
name = "py-loop"
version = "0.4.1"
description = "Run commands until it fails"
authors = ["jerem <jeremy.tellaa@tanker.io>"]

[tool.poetry.dependencies]
python = "^3.7"
cli-ui = "^0.17.2"

[tool.poetry.dev-dependencies]
black = "22.8.0"
codecov = "^2.0.22"
flake8 = "5.0.4"
mypy = "0.982"
pytest = "^7.1.3"
pytest-cov = "^4.0.0"
types-setuptools = "^65.4.0.0"
isort = "^5.10.1"

[tool.poetry.group.dev.dependencies]
twine = "^4.0.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
looper = 'py_loop.main:main'
