[tool.poetry]
name = "py-loop"
version = "0.4.0"
description = "Run commands until it fails"
authors = ["jerem <jeremy.tellaa@tanker.io>"]

[tool.poetry.dependencies]
python = "^3.7"
cli-ui = "^0.10.2"

[tool.poetry.dev-dependencies]
black = "21.12b0"
codecov = "^2.0.22"
flake8 = "4.0.1"
mypy = "0.931"
pytest = "^6.2.5"
pytest-cov = "^2.8.1"
types-setuptools = "^57.4.7"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
looper = 'py_loop.main:main'
