[tool.poetry]
name = "py-loop"
version = "0.4.1"
description = "Run commands until it fails"
authors = ["jerem <jeremy.tellaa@tanker.io>"]

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
cli-ui = "^0.17.2"

[tool.poetry.dev-dependencies]
black = "23.3.0"
codecov = "^2.01.13"
flake8 = "6.0.0"
mypy = "1.2.0"
pytest = "^7.3.1"
pytest-cov = "^4.0.0"
types-setuptools = "^67.6.0.8"
isort = "^5.12.0"

[tool.poetry.group.dev.dependencies]
twine = "^4.0.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
looper = 'py_loop.main:main'
